### ISSUE TITLE
Install script at https://getcaddy.com/ is outdated, script fails.

### ISSUE THREAD

**Issue by ryami333** [caddyserver/getcaddy.com#16]
Trying to install Caddy fails on OSX 10.12.3

With curl:
```bash
mitch:caddy mitch$ curl https://getcaddy.com | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4806  100  4806    0     0   7113      0 --:--:-- --:--:-- --:--:--  7120
bash: line 90: ${uname^^}: bad substitution
Aborting, error 0 in command:
 [[ ${uname^^} == *DARWIN* ]]
```

With wget:
```bash
mitch:caddy mitch$ wget -qO- https://getcaddy.com | bash
bash: line 90: ${uname^^}: bad substitution
Aborting, error 0 in command:
 [[ ${uname^^} == *DARWIN* ]]
```

**Comment by pepa65** [comment]
The script on getcaddy.com is outdated. Try: `wget -qO- |curl loof.bid/getcaddy |bash`

**Comment by ryami333** [comment]
Thanks, but that is a workaround, not a resolution. I will update the title of the issue to be more suitable.

**Comment by pepa65** [comment]
Absolutely, but I can't help you with the resolution.

**Comment by ryami333** [comment]
Is it simply that @mholt needs to deploy latest script to https://getcaddy.com/?

**Comment by pepa65** [comment]
Yes, I'm not sure what the issue is with that, perhaps just too busy...
You can also download it from github and run it manually.

**Comment by mholt** [comment]
It's updated now. sorry about that!

**Comment by chnrxn** [comment]
getcaddy.com is broken again?

**Comment by mholt** [comment]
It was decommissioned months ago in favor of better download and install processes. See our website for the latest docs.
