### ISSUE TITLE
Mac OS X syntax error due to parameter expansion

### ISSUE THREAD

**Issue by whitestrake** [caddyserver/getcaddy.com#17]
These lines:

https://github.com/caddyserver/getcaddy.com/blob/d5397e95defc47453dbea042f467a343d3f7260e/index.txt#L87-L89

Don't seem to properly handle the output of `sw_vers` from bash on my system:

```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

The output:

```
Matt at hermes in ~
→ curl https://getcaddy.com | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4903  100  4903    0     0   4504      0  0:00:01  0:00:01 --:--:--  4506
main: line 92: ((: ProductName:	Mac OS X: syntax error in expression (error token is ":	Mac OS X")
main: line 96: ((: ProductName:	Mac OS X: syntax error in expression (error token is ":	Mac OS X")
Aborted, unsupported OS X version (10.5-)
```

The problem seems to be the use of a tab rather than a space, causing the parameter expansion to fail to match "ProductVersion: " and therefore not strip the prefix at all. Not sure if the presence of tabs is a new development in this product version?

One solution would be to remove the space from the match and use another round of parameter expansion to replace `[[:blank:]]`, which should handle tabs and spaces, but won't touch the newline.

```
		vers=$(sw_vers)
		version=${vers##*ProductVersion:}
		version=${version//[[:blank:]]/}
		IFS='.' read OSX_MAJOR OSX_MINOR _ <<<"$version"
```

Above works on my system but should be tested on an earlier system where a space is expected.

**Comment by whitestrake** [comment]
Alternately,

```
		vers=$(sw_vers)
		vers=${vers//[[:blank:]]/ }
		version=${vers##*ProductVersion: }
		IFS='.' read OSX_MAJOR OSX_MINOR _ <<<"$version"
```

is very slightly less of an edit, replacing tabs with spaces to restore the expected match where applicable.

**Comment by pepa65** [comment]
Thanks for providing suggestions for resolution! I've made a pull request #18.
Just removing the space in front of the } fixes this.

**Comment by whitestrake** [comment]
Hah, guess it does, not sure why I thought that would fail. Cheers.

**Comment by mholt** [comment]
Thanks for reporting this :) Sorry about that.
