### ISSUE TITLE
API to list available plugins

### ISSUE THREAD

**Issue by coolaj86** [caddyserver/getcaddy.com#19]
I'm working on an installer script and I'd like `--help` to be able to show the available plugins.

It'd be great to have a resource with all of the plugin names both as json and some sort of text format - probably something that either has a header for each set of plugins (dns, tls, http) or a column with the plugin type.

(on that note it's important to distinguish between http and tls, because tls could be used for all sorts of things in the future - sni-based proxying, smtp, irc, who knows)

**Comment by pepa65** [comment]
I had the same question. The new Caddy, due soon, will have this all more integrated. In the meantime, you can look how I did this in bash:
https://github.com/pepa65/getcaddy.com/tree/upgrade

**Comment by mholt** [comment]
When we do this, I'm thinking of having plugins that don't actually exist added to the list randomly (between one and three, maybe, for each response) - to ensure that people aren't blindly adding all plugins, which effectively would allow anyone to execute arbitrary, remotely-published code on their servers. (Chrome does this kind of thing with GREASE.)

**Comment by pepa65** [comment]
I had another idea, which I think would be great. How about have the default upgrade action (without any additional commandline options) be to download the updated binary with all the currently installed plugins? That is probably what most servers would need for the most automatic upgrade experience.
