### ISSUE TITLE
Verifying Archive Signatures

### ISSUE THREAD

**Issue by MatthewVance** [caddyserver/getcaddy.com#29]
It would be good to incorporate some logic to verify the PGP signature as part of the install script. 

I mocked up the following to show how this might be done. This is untested, but should give some general ideas if we want to officially tackle this (would need to add check to confirm gnupg is installed before running the check).

```
# Set PGP key used to sign Caddy
export PGP_CADDY=65760C51EDEA2017CEA2CA15155B6D79CA56EA34

# Download the signature file
curl -fsSL https://caddyserver.com/download/$caddy_os/$caddy_arch/signature/$caddy_arm?plugins=$caddy_plugins -o $PREFIX/tmp/caddy.tar.gz.asc

gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$PGP_CADDY"
gpg --batch --verify $PREFIX/tmp/caddy.tar.gz.asc $PREFIX/tmp/$caddy_file
rm $PREFIX/tmp/caddy.tar.gz.asc 
```

**Comment by mholt** [comment]
This is a good idea. I second you in that we should do this only if the gpg command is present. Also, we can download the key directly from Keybase: https://keybase.io/caddy/pgp_keys.asc?fingerprint=65760c51edea2017cea2ca15155b6d79ca56ea34

**Comment by pepa65** [comment]
Does every download come with a corresponding .asc file already??

**Comment by mholt** [comment]
@pepa65 It's a separate download, but yes, there's a signature file for every download.

**Comment by pepa65** [comment]
So how does that work with the plugins?? If say this package gets downloaded: `https://caddyserver.com/download/openbsd/arm6?plugins=http.cors,tls.dns.ovh`, what would the corresponding url for the asc file be?

**Comment by MatthewVance** [comment]
It would be like 
https://caddyserver.com/download/linux/386/signature?plugins=http.authz

After selecting the plugins you want, click the Download PGP Signature link under the main download button to see the format for the asc file.

**Comment by MatthewVance** [comment]
Thanks. I haven't forgotten this. Just need some free time to work on it.

**Comment by pepa65** [comment]
I got this working (PR 35).
(I was going to ask you for a review Matthew, but the interface wouldn't let me, so considerer this an informal request for review.)
