### ISSUE TITLE
Aborted, error 2 in command: gpg

### ISSUE THREAD

**Issue by scheesman** [caddyserver/getcaddy.com#38]
I am running into an issue trying to install Caddy from the CLI. I have replicated the issue on 2 clean install Ubuntu 16.04 installs on GCE. Here is the command and output I am running:
```
root@web-1:/home/scheesman# curl https://getcaddy.com | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5593  100  5593    0     0  12837      0 --:--:-- --:--:-- --:--:-- 12857
Downloading Caddy for linux/amd64...
https://caddyserver.com/download/linux/amd64?plugins=
Aborted, error 2 in command: gpg --keyserver ha.pool.sks-keyservers.net --recv-keys $caddy_pgp > /dev/null 2>&1
root@web-1:/home/scheesman#
```
It doesn't make a difference if I run it as sudo or even as root (as in that example). I can set up a fresh VM if you would like to see it hands-on.

**Comment by pepa65** [comment]
What happens (output) when you execute `gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 65760C51EDEA2017CEA2CA15155B6D79CA56EA34` on the commandline??

**Comment by scheesman** [comment]
Interesting...
```
scheesman@web-1:~$ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 65760C51EDEA2017CEA2CA15155B6D79CA56EA34
gpg: requesting key CA56EA34 from hkp server ha.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
scheesman@web-1:~$
```
Took 2 minutes to run and time out (via `time gpg --keyserver...` command).
```
scheesman@web-1:~$ nslookup ha.pool.sks-keyservers.net
Server:		169.254.169.254
Address:	169.254.169.254#53

Non-authoritative answer:
Name:	ha.pool.sks-keyservers.net
Address: 37.191.238.78
Name:	ha.pool.sks-keyservers.net
Address: 208.113.128.181
Name:	ha.pool.sks-keyservers.net
Address: 79.143.214.213
Name:	ha.pool.sks-keyservers.net
Address: 104.236.209.43
Name:	ha.pool.sks-keyservers.net
Address: 178.32.66.144
Name:	ha.pool.sks-keyservers.net
Address: 67.205.148.255
```
I can ping them all except for `37.191.238.78`, so maybe it's not failing over to the additional records?

**Comment by scheesman** [comment]
Ok, here's what I did.  I edited `/etc/hosts` and added a static entry for `ha.pool.sks-keyservers.net`.  `208.113.128.181` returned a `connection refused`.  `79.143.214.213` worked, and I was able to run both the gpg command directly as well as the getcaddy.com bash script itself.  So it look like there may be some issues with `ha.pool.sks-keyservers.net` itself.

**Comment by pepa65** [comment]
Very resourceful! I don't know if there are additional commandline flags to make this work smoother; if so, they should be added I think.

We should keep this issue open for now I think until we have more clarity.

**Comment by scheesman** [comment]
I didn't see any `--keyserver-options` options that looked relevant to me.  I think these issues aren't supposed to be happening, and wouldn't spend too much time trying to plan for them.  I just reran `nslookup` and got different results this time, so they may be aware and are working on it
```
Non-authoritative answer:
Name:	ha.pool.sks-keyservers.net
Address: 67.205.148.255
Name:	ha.pool.sks-keyservers.net
Address: 79.143.214.213
Name:	ha.pool.sks-keyservers.net
Address: 37.191.226.104
Name:	ha.pool.sks-keyservers.net
Address: 45.77.40.159
Name:	ha.pool.sks-keyservers.net
Address: 178.32.66.144
```
Thanks for the step in the right direction on the gpg command!  I'm not much of a programmer, so I was having trouble stepping thru the script.

**Comment by mholt** [comment]
Thanks for looking into this, you two! (And thanks for reposting the issue here.)

**Comment by pepa65** [comment]
Another instance of the same problem:
https://caddy.community/t/installing-caddy-on-raspberry-pi/2686

**Comment by vintagesucks** [comment]
I ran into this error several times during some travis/docker builds and ended up [replacing](https://github.com/vintagesucks/caddy-script/commit/755a925d418aaabfe6774464ffe961a31ff5f9f8) `ha.pool.sks-keyservers.net` with `keyserver.ubuntu.com`—not an ideal solution but I never ran into this error again.

This seems to be a [common issue](https://github.com/search?utf8=%E2%9C%93&q=gpg+ha.pool.sks-keyservers.net&type=Issues).

**Comment by pepa65** [comment]
Maybe we should try another subset of the larger pool. The ha pool is supposed to be "a high-availibility subset of the pool that require all servers to be identified as a clustered setup". (See: https://sks-keyservers.net/overview-of-pools.php)

Maybe people with this problem can try changing `ha.pool.sks-keyservers.net` into something else as listed on the *Overview of pools* page. I would try `pool.sks-keyservers.net` or `hkps.pool.sks-keyservers.net` and see whether that is any better.

**And please report back so we can fix this for everyone..!** (-:

**Comment by pepa65** [comment]
I always use `keyserver.ubuntu.com` (but I'm biassed). It is really fast, and works as well.

This issue does seem to hit many different projects that try to use `ha.pool.sks-keyservers.net`...

**Comment by pepa65** [comment]
@mholt One way to make this more robust is to check for error 2 and try a list of keyservers. (Or just pick one that seems to work better overall.)

**Comment by mholt** [comment]
@pepa65 We could try that. Would it be complicated?

**Comment by pepa65** [comment]
@mholt I'll make a featurebranch with it, should be fairly easy. The biggest issue is which keyservers to pick -- but we can always adjust those,
