### ISSUE TITLE
No valid response from keyservers

### ISSUE THREAD

**Issue by uchagani** [caddyserver/getcaddy.com#43]
Trying to install caddy this evening and am getting the following error, although install completes successfully:

`No valid response from keyservers`

full shell message:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0  21340      0 --:--:-- --:--:-- --:--:-- 21391
Downloading Caddy for linux/amd64 (personal license)...
No valid response from keyservers
Extracting...
Putting caddy in /usr/local/bin (may require password)
Caddy 0.11.4 (non-commercial use only)
Successfully installed
```

**Comment by mholt** [comment]
The key server was inaccessible at that time. If you're concerned, you can download the archive yourself, and check its signature manually. https://github.com/mholt/caddy/wiki/Verifying-Archive-Signatures
