### ISSUE TITLE
Script errors with 404

### ISSUE THREAD

**Issue by sjennison** [caddyserver/getcaddy.com#45]
Attempting to install caddy using getcaddy.com results in the following error:
```wget -qO- https://getcaddy.com | bash -s personal
⚠️ This installer only supports v1, which is obsoleted now that Caddy 2 is released. This script may change or go away soon. Please upgrade: https://caddyserver.com/docs/v2-upgrade
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 404 
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
```

Is getcaddy.com no longer usable? If so, is there an alternative? The script output doesn't indicate it's obsolete (only that it may change or go away soon), and as far as I can tell there's no alternative.

**Comment by mholt** [comment]
getcaddy.com has been turned off because it doesn't support v2, and v1 is no longer supported.

> The script output doesn't indicate it's obsolete

Huh? Yes it does:

> This installer only supports v1, which is obsoleted now

We have a variety of install methods for v2: https://caddyserver.com/docs/download

Including a new download page (please don't script against it though): https://caddyserver.com/download

**Comment by sjennison** [comment]
> Huh? Yes it does:

Fair enough - maybe the text should be changed to indicate it's currently/intentionally broken - as opposed to "may change or go away soon"?

> We have a variety of install methods for v2: https://caddyserver.com/docs/download

~~None of those appear to be the same as getcaddy.com though - they don't install, automatically, to the "correct" location for the OS, which was super convenient. If that kind of thing isn't a thing you'll provide now, that's OK I guess, just a little disappointing.~~
Or I'm just an idiot and didn't read the page all the way... never mind! The packages are perfect!
